### ISSUE TITLE
Instanz bleibt rot, Fehlerschleife, ioBroker in VM Proxmox

### ISSUE THREAD

**Issue by gidhap** [soef/ioBroker.tr-064#100]
Hallo, meine instanz bleibt rot, das LOG zeigt immer die gleiche Fehlerschleife...
Hilfe ist willkommen :o)
`

host.iobroker-vm | 2020-02-14 18:26:04.151 | info | Restart adapter system.adapter.tr-064.0 because enabled
-- | -- | -- | --
host.iobroker-vm | 2020-02-14 18:26:04.151 | error | instance system.adapter.tr-064.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
host.iobroker-vm | 2020-02-14 18:26:04.151 | error | Caught by controller[0]:     at internal/main/run_main_module.js:17:47
host.iobroker-vm | 2020-02-14 18:26:04.151 | error | Caught by controller[0]:     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
host.iobroker-vm | 2020-02-14 18:26:04.151 | error | Caught by controller[0]:     at Function.Module._load (internal/modules/cjs/loader.js:899:14)
host.iobroker-vm | 2020-02-14 18:26:04.151 | error | Caught by controller[0]:     at Module.load (internal/modules/cjs/loader.js:1000:32)
host.iobroker-vm | 2020-02-14 18:26:04.151 | error | Caught by controller[0]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
host.iobroker-vm | 2020-02-14 18:26:04.150 | error | Caught by controller[0]:     at Module._compile (internal/modules/cjs/loader.js:1151:30)
host.iobroker-vm | 2020-02-14 18:26:04.150 | error | Caught by controller[0]:     at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.tr-064/tr-064.js:15:20)
host.iobroker-vm | 2020-02-14 18:26:04.144 | error | Caught by controller[0]:     at Object.exports.Adapter (/opt/iobroker/node_modules/soef/soef.js:1383:23)
host.iobroker-vm | 2020-02-14 18:26:04.144 | error | Caught by controller[0]: TypeError: fns.adapter is not a function
host.iobroker-vm | 2020-02-14 18:26:04.144 | error | Caught by controller[0]:                       ^
host.iobroker-vm | 2020-02-14 18:26:04.144 | error | Caught by controller[0]:     fns.adapter = fns.adapter(options);
host.iobroker-vm | 2020-02-14 18:26:04.144 | error | Caught by controller[0]: /opt/iobroker/node_modules/soef/soef.js:1383
host.iobroker-vm | 2020-02-14 18:26:03.796 | info | instance system.adapter.tr-064.0 started with pid 3363

`

**Comment by gidhap** [comment]
workaround gefunden - Quelle: https://github.com/soef/ioBroker.wifili … -351513299
