### ISSUE TITLE
adapter does not start !

### ISSUE THREAD

**Issue by josefa94** [soef/ioBroker.tr-064#101]
hey guys,
i have install a brandnew Version on Iobroker(3.7.8) and this Adapter does not start.
can somebody help me? , following are the error codes

thx josef 

host.Iobroker | 2020-03-31 20:14:31.412 | error | instance system.adapter.tr-064.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
-- | -- | -- | --
host.Iobroker | 2020-03-31 20:14:31.412 | error | Caught by controller[0]:     at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
host.Iobroker | 2020-03-31 20:14:31.412 | error | Caught by controller[0]:     at startup (internal/bootstrap/node.js:283:19)
host.Iobroker | 2020-03-31 20:14:31.412 | error | Caught by controller[0]:     at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
host.Iobroker | 2020-03-31 20:14:31.411 | error | Caught by controller[0]:     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
host.Iobroker | 2020-03-31 20:14:31.411 | error | Caught by controller[0]:     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
host.Iobroker | 2020-03-31 20:14:31.411 | error | Caught by controller[0]:     at Module.load (internal/modules/cjs/loader.js:653:32)
host.Iobroker | 2020-03-31 20:14:31.411 | error | Caught by controller[0]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
host.Iobroker | 2020-03-31 20:14:31.411 | error | Caught by controller[0]:     at Module._compile (internal/modules/cjs/loader.js:778:30)
host.Iobroker | 2020-03-31 20:14:31.411 | error | Caught by controller[0]:     at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.tr-064/tr-064.js:15:20)
host.Iobroker | 2020-03-31 20:14:31.411 | error | Caught by controller[0]:     at Object.exports.Adapter (/opt/iobroker/node_modules/soef/soef.js:1383:23)
host.Iobroker | 2020-03-31 20:14:31.410 | error | Caught by controller[0]: TypeError: fns.adapter is not a function
host.Iobroker | 2020-03-31 20:14:31.410 | error | Caught by controller[0]:                       ^
host.Iobroker | 2020-03-31 20:14:31.410 | error | Caught by controller[0]:     fns.adapter = fns.adapter(options);
host.Iobroker | 2020-03-31 20:14:31.410 | error | Caught by controller[0]: /opt/iobroker/node_modules/soef/soef.js:1383

**Comment by matze19999** [comment]
service iobroker start && cd /opt/iobroker/node_modules/iobroker.tr-064/ && npm install soef
