### ISSUE TITLE
adapter crashes when adding more than one watchable device

### ISSUE THREAD

**Issue by jens-maus** [soef/ioBroker.tr-064#3]
Here the adapter crashes as soon as I add a second device for monitoring its online status:

```

host.bilbo	2016-11-15 21:40:30.088	info	Restart adapter system.adapter.tr-064.0 because enabled
host.bilbo	2016-11-15 21:40:30.088	error	instance system.adapter.tr-064.0 terminated with code 0 (OK)
tr-064.0	2016-11-15 21:40:30.084	info	terminating
tr-064.0	2016-11-15 21:40:30.082	error	at Object.onclosetag (/opt/iobroker/node_modules/iobroker.tr-064/node_modules/xml2js/lib/xml2js.js:447:26)
tr-064.0	2016-11-15 21:40:30.082	error	at Parser.emit (events.js:169:7)
tr-064.0	2016-11-15 21:40:30.082	error	at emitOne (events.js:77:13)
tr-064.0	2016-11-15 21:40:30.082	error	at Parser. (/opt/iobroker/node_modules/iobroker.tr-064/node_modules/xml2js/lib/xml2js.js:489:18)
tr-064.0	2016-11-15 21:40:30.082	error	at /opt/iobroker/node_modules/iobroker.tr-064/node_modules/tr-O64/lib/Service.js:267:17
tr-064.0	2016-11-15 21:40:30.082	error	at /opt/iobroker/node_modules/iobroker.tr-064/tr-064.js:263:21
tr-064.0	2016-11-15 21:40:30.082	error	at /opt/iobroker/node_modules/iobroker.tr-064/tr-064.js:412:9
tr-064.0	2016-11-15 21:40:30.082	error	at setActive (/opt/iobroker/node_modules/iobroker.tr-064/tr-064.js:401:14)
tr-064.0	2016-11-15 21:40:30.082	error	at CDevice.set (/opt/iobroker/node_modules/iobroker.tr-064/node_modules/soef/soef.js:819:24)
tr-064.0	2016-11-15 21:40:30.082	error	at add (/opt/iobroker/node_modules/iobroker.tr-064/node_modules/soef/soef.js:790:21)
tr-064.0	2016-11-15 21:40:30.082	error	TypeError: Cannot set property '_id' of undefined
tr-064.0	2016-11-15 21:40:30.080	error	uncaught exception: Cannot set property '_id' of undefined
tr-064.0	2016-11-15 21:40:28.431	info	starting. Version 0.1.7 in /opt/iobroker/node_modules/iobroker.tr-064, node: v4.6.2
```

**Comment by Apollon77** [comment]
Update soef library in the adapter directory to current version fixes this

**Comment by Apollon77** [comment]
should be fixed in the meantime?!
