### ISSUE TITLE
Fehler mit Version 0.3.17

### ISSUE THREAD

**Issue by ldittmar81** [soef/ioBroker.tr-064#32]
Im Log erscheint die ganze Zeit:

```
host.RackStation   2017-06-06 19:15:09.507   error   instance system.adapter.tr-064.0 terminated with code 1 ()
```
Wenn man im Terminal "node node_modules/iobroker.tr-064/tr-064.js --logs --force" eingibt kommt
```
/opt/iobroker/node_modules/soef/soef.js:1253                                    
    fns.adapter = fns.adapter(options);                                         
                      ^                                                         
                                                                                
TypeError: fns.adapter is not a function                                        
    at Object.exports.Adapter (/opt/iobroker/node_modules/soef/soef.js:1253:23) 
    at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.tr-064/tr-064.js:14:20)                                                                          
    at Module._compile (module.js:570:32)                                       
    at Object.Module._extensions..js (module.js:579:10)                         
    at Module.load (module.js:487:32)                                           
    at tryModuleLoad (module.js:446:12)                                         
    at Function.Module._load (module.js:438:3)                                  
    at Module.runMain (module.js:604:10)                                        
    at run (bootstrap_node.js:390:7)                                            
    at startup (bootstrap_node.js:150:9)
```
Siehe auch im Forum: http://forum.iobroker.net/viewtopic.php?f=22&t=6762

**Comment by soef** [comment]
Hallo, sorry für die späte Antwort, war im Urlaub. Leider kann nicht das Problem nicht nachvollziehen. Welche Node version und welches Betriebssystem wird benutzt?

**Comment by Apollon77** [comment]
Bei Lightify-Adapter sind die tests aktuell mit gleichem Fehler defekt

**Comment by soef** [comment]
Ist in Version 0.3.21 gefixed. Neue Version (0.4.4) der soef lib. Ist aktuell noch nicht auf npm. Ich warte noch ein paar Tage um alles zu verifizieren, dann werde ich auch npm updaten.
Die Fehler, auch in iobroker.lightify, beruhen auf einer Änderung in der utils.js. Früher wurde adapter in Kleinbuchstaben, aktuell mit einem ersten großen Buchstaben exportiert. Also Adapter. Neueres ist aber "korrekter". Grüße...
