### ISSUE TITLE
Update auf 0.4.8 funktioniert nicht

### ISSUE THREAD

**Issue by pancho23** [soef/ioBroker.tr-064#49]
$ ./iobroker url "https://github.com/soef/ioBroker.tr-064/tarball/master" tr-064
install https://github.com/soef/ioBroker.tr-064/tarball/master
npm install https://github.com/soef/ioBroker.tr-064/tarball/master --production --prefix "C:/ioBroker" (System call)
got C:/ioBroker/node_modules/iobroker.tr-064/admin
upload [2] tr-064.admin C:/ioBroker/node_modules/iobroker.tr-064/admin/words.js words.js application/javascript
upload [1] tr-064.admin C:/ioBroker/node_modules/iobroker.tr-064/admin/tr-064.png tr-064.png image/png
upload [0] tr-064.admin C:/ioBroker/node_modules/iobroker.tr-064/admin/index.html index.html text/html
ERROR: module.js:427
    throw err;
    ^

SyntaxError: C:\ioBroker\node_modules\iobroker.tr-064\io-package.json: Unexpected token ,
    at Object.parse (native)
    at Object.Module._extensions..json (module.js:424:27)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Upload.uploadAdapter (C:\ioBroker\node_modules\iobroker.js-controller\lib\setup\setupUpload.js:214:23)
    at C:\ioBroker\node_modules\iobroker.js-controller\lib\setup.js:697:40
    at upload (C:\ioBroker\node_modules\iobroker.js-controller\lib\setup\setupUpload.js:280:57)
    at null._onTimeout (C:\ioBroker\node_modules\iobroker.js-controller\lib\setup\setupUpload.js:332:29)

ERROR: process exited with code 1

**Comment by soef** [comment]
Oh, da war die io-package.json zerschossen. Ist in 0.4.9 korrigiert.
