### ISSUE TITLE
Probleme bei der Aktualisierung des Adapters

### ISSUE THREAD

**Issue by Borti86** [soef/ioBroker.tr-064#95]
Hallo zusammen,
ich habe versucht den Adapter im IOBroker zu aktualisieren, leider bekomme ich folgende Fehlermeldung. Wo könnte das Problem liegen?
Für eure Mühe möchte ich mich im Voraus bedanken!

Liebe Grüße
Borti

`$ ./iobroker upgrade tr-064
Update tr-064 from @0.4.14 to @0.4.18
NPM version: 6.11.3
npm install iobroker.tr-064@0.4.18 --production --save --prefix "/opt/iobroker" (System call)
npm
 WARN 
checkPermissions Missing write access to /opt/iobroker/node_modules/iobroker.tr-064/node_modules/array-ext
npm WARN checkPermissions Missing write access to /opt/iobroker/node_modules/iobroker.tr-064/node_modules/dgramnpm WARN checkPermissions Missing write access to /opt/iobroker/node_modules/iobroker.tr-064/node_modules/ip
npm WARN checkPermissions Missing write access to /opt/iobroker/node_modules/iobroker.tr-064/node_modules/safe-buffer
npm WARN checkPermissions Missing write access to /opt/iobroker/node_modules/iobroker.tr-064/node_modules/dns-packet
npm WARN checkPermissions Missing write access to /opt/iobroker/node_modules/iobroker.tr-064/node_modules/sprintf-js
npm WARN checkPermissions Missing write access to /opt/iobroker/node_modules/iobroker.tr-064/node_modules/soef

npm
 
WARN 
enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/iobroker.tradfri/package.json'
npm
 WARN
 bl@0.7.0 requires a peer of stream-browserify@* but none is installed. You must install peer dependencies yourself.npm
 WARN
 bl@0.7.0 requires a peer of stream-browserify@* but none is installed. You must install peer dependencies yourself.
npm
 WARN @typescript-eslint/eslint-plugin@1.12.0 requires a peer of eslint@^5.0.0 but none is installed. You must install peer dependencies yourself.npm WARN @typescript-eslint/parser@1.12.0 requires a peer of eslint@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN bl@0.7.0 requires a peer of stream-browserify@* but none is installed. You must install peer dependencies yourself.

npm
 ERR!
 code EACCESnpm ERR! syscall access
npm ERR! path /opt/iobroker/node_modules/iobroker.tr-064/node_modules/array-ext
npm
 ERR! errno -13
npm ERR! Error: EACCES: permission denied, access '/opt/iobroker/node_modules/iobroker.tr-064/node_modules/array-ext'npm ERR!  { [Error: EACCES: permission denied, access '/opt/iobroker/node_modules/iobroker.tr-064/node_modules/array-ext']
npm ERR!   stack:
npm ERR!
    'Error: EACCES: permission denied, access \'/opt/iobroker/node_modules/iobroker.tr-064/node_modules/array-ext\'',npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path:
npm ERR!    '/opt/iobroker/node_modules/iobroker.tr-064/node_modules/array-ext' }

npm ERR! npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm 
ERR! If you believe this might be a permissions issue, please double-check thenpm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:npm ERR!     /home/iobroker/.npm/_logs/2019-09-17T13_01_30_485Z-debug.log

ERROR: host.raspberrypi Cannot install iobroker.tr-064@0.4.18: 243
ERROR: process exited with code 25`

**Comment by Borti86** [comment]
Bei dem Versuch einer Deinstallation kommt folgende Fehlermeldung

$ ./iobroker del tr-064
Delete adapter "tr-064"
host.raspberrypi Counted 1 states of tr-064
host.raspberrypi Counted 1 states (system.adapter.tr-064.*) from states
host.raspberrypi Deleting 1 object(s).
host.raspberrypi Deleting 1 state(s).
npm uninstall iobroker.tr-064 --silent --save --prefix "/opt/iobroker" (System call)
ERROR: Error deleting adapter tr-064 from disk: Error: host.raspberrypi: Cannot uninstall iobroker.tr-064: 243
ERROR: You might have to delete it yourself!
process exited with code 0

**Comment by bergjet** [comment]
Selber Fehler bei der Installation:

`$ ./iobroker upgrade tr-064@0.4.18
Update tr-064 from @0.4.18 to @0.4.18
NPM version: 6.11.3
npm install iobroker.tr-064@0.4.18 --loglevel error --production --save --prefix "/opt/iobroker" (System call)
npm
 ERR! code EACCESnpm ERR! syscall accessnpm ERR! path /opt/iobroker/node_modules/iobroker.tr-064/node_modules/array-extnpm ERR! errno -13
npm
 ERR! Error: EACCES: permission denied, access '/opt/iobroker/node_modules/iobroker.tr-064/node_modules/array-ext'npm ERR!  { [Error: EACCES: permission denied, access '/opt/iobroker/node_modules/iobroker.tr-064/node_modules/array-ext']npm ERR!   stack:npm ERR!    'Error: EACCES: permission denied, access \'/opt/iobroker/node_modules/iobroker.tr-064/node_modules/array-ext\'',npm ERR!   errno: -13,npm ERR!   code: 'EACCES',npm ERR!   syscall: 'access',npm
 ERR!   path:npm ERR!    '/opt/iobroker/node_modules/iobroker.tr-064/node_modules/array-ext' }npm ERR! npm ERR! The operation was rejected by your operating system.npm 
ERR! It is likely you do not have the permissions to access this file as the current usernpm ERR! npm ERR! If you believe this might be a permissions issue, please double-check thenpm ERR! permissions of the file and its containing directories, or try runningnpm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:npm ERR!     /home/iobroker/.npm/_logs/2019-10-18T16_19_33_601Z-debug.log
ERROR: host.raspberrypi Cannot install iobroker.tr-064@0.4.18: 243
ERROR: process exited with code 25`

**Comment by salopette** [comment]
Ich kann meinen Adapter auch nicht deinstallieren und auch nicht aktualisieren, kann mir da einer weiter helfen?

**Comment by 1onar** [comment]
Ich kann den Adapter auch nicht installieren.

> $ ./iobroker url "https://github.com/iobroker-community-adapters/ioBroker.tr-064-community"
install https://github.com/iobroker-community-adapters/ioBroker.tr-064-community/tarball/b8b8aa25a464f2d81915a1322a3f2739164fcefe
NPM version: 6.13.4
npm install https://github.com/iobroker-community-adapters/ioBroker.tr-064-community/tarball/b8b8aa25a464f2d81915a1322a3f2739164fcefe --loglevel error --prefix "/opt/iobroker" (System call)
In file included from ../src/./serialport.h:6,                 from ../src/serialport.cpp:1:../../nan/nan.h: In function ‘void Nan::AsyncQueueWorker(Nan::AsyncWorker*)’:../../nan/nan.h:2298:62: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]     , reinterpret_cast<uv_after_work_cb>(AsyncExecuteComplete)                                                              ^
../src/serialport.cpp: In function ‘Nan::NAN_METHOD_RETURN_TYPE Open(Nan::NAN_METHOD_ARGS_TYPE)’:../src/serialport.cpp:41:48: error: no matching function for call to ‘v8::Value::ToString()’   v8::String::Utf8Value path(info[0]->ToString());                                                ^
In file included from /home/iobroker/.cache/node-gyp/12.15.0/include/node/node.h:63,                 from ../../nan/nan.h:54,                 from ../src/./serialport.h:6,                 from ../src/serialport.cpp:1:/home/iobroker/.cache/node-gyp/12.15.0/include/node/v8.h:2572:44: note: candidate: ‘v8::MaybeLocal<v8::String> v8::Value::ToString(v8::Local<v8::Context>) const’   V8_WARN_UNUSED_RESULT MaybeLocal<String> ToString(                                            ^~~~~~~~/home/iobroker/.cache/node-gyp/12.15.0/include/node/v8.h:2572:44: note:   candidate expects 1 argument, 0 provided
In file included from /home/iobroker/.cache/node-gyp/12.15.0/include/node/v8-internal.h:14,                 from /home/iobroker/.cache/node-gyp/12.15.0/include/node/v8.h:25,                 from /home/iobroker/.cache/node-gyp/12.15.0/include/node/node.h:63,                 from ../../nan/nan.h:54,                 from ../src/./serialport.h:6,                 from ../src/serialport.cpp:1:/home/iobroker/.cache/node-gyp/12.15.0/include/node/v8.h:2588:31: note: candidate: ‘v8::Local<v8::String> v8::Value::ToString(v8::Isolate*) const’                 Local<String> ToString(Isolate* isolate) const);                               ^~~~~~~~/home/iobroker/.cache/node-gyp/12.15.0/include/node/v8config.h:311:3: note: in definition of macro ‘V8_DEPRECATED’   declarator __attribute__((deprecated(message)))   ^~~~~~~~~~/home/iobroker/.cache/node-gyp/12.15.0/include/node/v8.h:2588:31: note:   candidate expects 1 argument, 0 provided                 Local<String> ToString(Isolate* isolate) const);                               ^~~~~~~~/home/iobroker/.cache/node-gyp/12.15.0/include/node/v8config.h:311:3: note: in definition of macro ‘V8_DEPRECATED’   declarator __attribute__((deprecated(message)))   ^~~~~~~~~~
../src/serialport.cpp:48:53: error: no matching function for call to ‘v8::Value::ToObject()’   v8::Local<v8::Object> options = info[1]->ToObject();                                                     ^In file included from /home/iobroker/.cache/node-gyp/12.15.0/include/node/node.h:63,                 from ../../nan/nan.h:54,                 from ../src/./serialport.h:6,                 from ../src/serialport.cpp:1:/home/iobroker/.cache/node-gyp/12.15.0/include/node/v8.h:2576:44: note: candidate: ‘v8::MaybeLocal<v8::Object> v8::Value::ToObject(v8::Local<v8::Context>) const’   V8_WARN_UNUSED_RESULT MaybeLocal<Object> ToObject(                                            ^~~~~~~~
/home/iobroker/.cache/node-gyp/12.15.0/include/node/v8.h:2576:44: note:   candidate expects 1 argument, 0 providedIn file included from /home/iobroker/.cache/node-gyp/12.15.0/include/node/v8-internal.h:14,                 from /home/iobroker/.cache/node-gyp/12.15.0/include/node/v8.h:25,                 from /home/iobroker/.cache/node-gyp/12.15.0/include/node/node.h:63,                 from ../../nan/nan.h:54,                 from ../src/./serialport.h:6,                 from ../src/serialport.cpp:1:/home/iobroker/.cache/node-gyp/12.15.0/include/node/v8.h:2590:31: note: candidate: ‘v8::Local<v8::Object> v8::Value::ToObject(v8::Isolate*) const’                 Local<Object> ToObject(Isolate* isolate) const);                               ^~~~~~~~/home/iobroker/.cache/node-gyp/12.15.0/include/node/v8config.h:311:3: note: in definition of macro ‘V8_DEPRECATED’   declarator __attribute__((deprecated(message)))   ^~~~~~~~~~
/home/iobroker/.cache/node-gyp/12.15.0/include/node/v8.h:2590:31: note:   candidate expects 1 argument, 0 provided                 Local<Object> ToObject(Isolate* isolate) const);                               ^~~~~~~~/home/iobroker/.cache/node-gyp/12.15.0/include/node/v8config.h:311:3: note: in definition of macro ‘V8_DEPRECATED’   declarator __attribute__((deprecated(message)))   ^~~~~~~~~~
../src/serialport.cpp:78:69: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]   uv_queue_work(uv_default_loop(), req, EIO_Open, (uv_after_work_cb)EIO_AfterOpen);                                                                     ^~~~~~~~~~~~~
../src/serialport.cpp: In function ‘void EIO_AfterOpen(uv_work_t*)’:../src/serialport.cpp:95:30: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is deprecated [-Wdeprecated-declarations]   data->callback.Call(2, argv);                              ^
In file included from ../src/./serialport.h:6,                 from ../src/serialport.cpp:1:../../nan/nan.h:1740:3: note: declared here   Call(int argc, v8::Local<v8::Value> argv[]) const {   ^~~~
../src/serialport.cpp: In function ‘Nan::NAN_METHOD_RETURN_TYPE Update(Nan::NAN_METHOD_ARGS_TYPE)’:../src/serialport.cpp:113:53: error: no matching function for call to ‘v8::Value::ToObject()’   v8::Local<v8::Object> options = info[1]->ToObject();                                                     ^
In file included from /home/iobroker/.cache/node-gyp/12.15.0/include/node/node.h:63,                 from ../../nan/nan.h:54,                 from ../src/./serialport.h:6,                 from ../src/serialport.cpp:1:/home/iobroker/.cache/node-gyp/12.15.0/include/node/v8.h:2576:44: note: candidate: ‘v8::MaybeLocal<v8::Object> v8::Value::ToObject(v8::Local<v8::Context>) const’   V8_WARN_UNUSED_RESULT MaybeLocal<Object> ToObject(                                            ^~~~~~~~/home/iobroker/.cache/node-gyp/12.15.0/include/node/v8.h:2576:44: note:   candidate expects 1 argument, 0 provided
In file included from /home/iobroker/.cache/node-gyp/12.15.0/include/node/v8-internal.h:14,                 from /home/iobroker/.cache/node-gyp/12.15.0/include/node/v8.h:25,                 from /home/iobroker/.cache/node-gyp/12.15.0/include/node/node.h:63,                 from ../../nan/nan.h:54,                 from ../src/./serialport.h:6,                 from ../src/serialport.cpp:1:/home/iobroker/.cache/node-gyp/12.15.0/include/node/v8.h:2590:31: note: candidate: ‘v8::Local<v8::Object> v8::Value::ToObject(v8::Isolate*) const’                 Local<Object> ToObject(Isolate* isolate) const);                               ^~~~~~~~/home/iobroker/.cache/node-gyp/12.15.0/include/node/v8config.h:311:3: note: in definition of macro ‘V8_DEPRECATED’   declarator __attribute__((deprecated(message)))   ^~~~~~~~~~/home/iobroker/.cache/node-gyp/12.15.0/include/node/v8.h:2590:31: note:   candidate expects 1 argument, 0 provided                 Local<Object> ToObject(Isolate* isolate) const);                               ^~~~~~~~/home/iobroker/.cache/node-gyp/12.15.0/include/node/v8config.h:311:3: note: in definition of macro ‘V8_DEPRECATED’   declarator __attribute__((deprecated(message)))   ^~~~~~~~~~
../src/serialport.cpp:135:71: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]   uv_queue_work(uv_default_loop(), req, EIO_Update, (uv_after_work_cb)EIO_AfterUpdate);                                                                       ^~~~~~~~~~~~~~~
../src/serialport.cpp: In function ‘void EIO_AfterUpdate(uv_work_t*)’:../src/serialport.cpp:150:30: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is deprecated [-Wdeprecated-declarations]   data->callback.Call(1, argv);                              ^
In file included from ../src/./serialport.h:6,                 from ../src/serialport.cpp:1:../../nan/nan.h:1740:3: note: declared here   Call(int argc, v8::Local<v8::Value> argv[]) const {   ^~~~
../src/serialport.cpp: In function ‘Nan::NAN_METHOD_RETURN_TYPE Close(Nan::NAN_METHOD_ARGS_TYPE)’:../src/serialport.cpp:175:70: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]   uv_queue_work(uv_default_loop(), req, EIO_Close, (uv_after_work_cb)EIO_AfterClose);                                                                      ^~~~~~~~~~~~~~
../src/serialport.cpp: In function ‘void EIO_AfterClose(uv_work_t*)’:../src/serialport.cpp:188:30: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is deprecated [-Wdeprecated-declarations]   data->callback.Call(1, argv);                              ^
In file included from ../src/./serialport.h:6,                 from ../src/serialport.cpp:1:../../nan/nan.h:1740:3: note: declared here   Call(int argc, v8::Local<v8::Value> argv[]) const {   ^~~~
../src/serialport.cpp: In function ‘Nan::NAN_METHOD_RETURN_TYPE Flush(Nan::NAN_METHOD_ARGS_TYPE)’:../src/serialport.cpp:215:70: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]   uv_queue_work(uv_default_loop(), req, EIO_Flush, (uv_after_work_cb)EIO_AfterFlush);                                                                      ^~~~~~~~~~~~~~
../src/serialport.cpp: In function ‘void EIO_AfterFlush(uv_work_t*)’:../src/serialport.cpp:231:30: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is deprecated [-Wdeprecated-declarations]   data->callback.Call(1, argv);                              ^
In file included from ../src/./serialport.h:6,                 from ../src/serialport.cpp:1:../../nan/nan.h:1740:3: note: declared here   Call(int argc, v8::Local<v8::Value> argv[]) const {   ^~~~
../src/serialport.cpp: In function ‘Nan::NAN_METHOD_RETURN_TYPE Set(Nan::NAN_METHOD_ARGS_TYPE)’:../src/serialport.cpp:250:53: error: no matching function for call to ‘v8::Value::ToObject()’   v8::Local<v8::Object> options = info[1]->ToObject();                                                     ^
In file included from /home/iobroker/.cache/node-gyp/12.15.0/include/node/node.h:63,                 from ../../nan/nan.h:54,                 from ../src/./serialport.h:6,                 from ../src/serialport.cpp:1:/home/iobroker/.cache/node-gyp/12.15.0/include/node/v8.h:2576:44: note: candidate: ‘v8::MaybeLocal<v8::Object> v8::Value::ToObject(v8::Local<v8::Context>) const’   V8_WARN_UNUSED_RESULT MaybeLocal<Object> ToObject(                                            ^~~~~~~~/home/iobroker/.cache/node-gyp/12.15.0/include/node/v8.h:2576:44: note:   candidate expects 1 argument, 0 provided
In file included from /home/iobroker/.cache/node-gyp/12.15.0/include/node/v8-internal.h:14,                 from /home/iobroker/.cache/node-gyp/12.15.0/include/node/v8.h:25,                 from /home/iobroker/.cache/node-gyp/12.15.0/include/node/node.h:63,                 from ../../nan/nan.h:54,                 from ../src/./serialport.h:6,                 from ../src/serialport.cpp:1:/home/iobroker/.cache/node-gyp/12.15.0/include/node/v8.h:2590:31: note: candidate: ‘v8::Local<v8::Object> v8::Value::ToObject(v8::Isolate*) const’                 Local<Object> ToObject(Isolate* isolate) const);                               ^~~~~~~~/home/iobroker/.cache/node-gyp/12.15.0/include/node/v8config.h:311:3: note: in definition of macro ‘V8_DEPRECATED’   declarator __attribute__((deprecated(message)))   ^~~~~~~~~~/home/iobroker/.cache/node-gyp/12.15.0/include/node/v8.h:2590:31: note:   candidate expects 1 argument, 0 provided                 Local<Object> ToObject(Isolate* isolate) const);                               ^~~~~~~~/home/iobroker/.cache/node-gyp/12.15.0/include/node/v8config.h:311:3: note: in definition of macro ‘V8_DEPRECATED’   declarator __attribute__((deprecated(message)))   ^~~~~~~~~~
../src/serialport.cpp:270:68: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]   uv_queue_work(uv_default_loop(), req, EIO_Set, (uv_after_work_cb)EIO_AfterSet);                                                                    ^~~~~~~~~~~~
../src/serialport.cpp: In function ‘void EIO_AfterSet(uv_work_t*)’:../src/serialport.cpp:285:30: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is deprecated [-Wdeprecated-declarations]   data->callback.Call(1, argv);                              ^
In file included from ../src/./serialport.h:6,                 from ../src/serialport.cpp:1:../../nan/nan.h:1740:3: note: declared here   Call(int argc, v8::Local<v8::Value> argv[]) const {   ^~~~
../src/serialport.cpp: In function ‘Nan::NAN_METHOD_RETURN_TYPE Get(Nan::NAN_METHOD_ARGS_TYPE)’:../src/serialport.cpp:314:68: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]   uv_queue_work(uv_default_loop(), req, EIO_Get, (uv_after_work_cb)EIO_AfterGet);                                                                    ^~~~~~~~~~~~
../src/serialport.cpp: In function ‘void EIO_AfterGet(uv_work_t*)’:../src/serialport.cpp:329:96: warning: ‘bool v8::Object::Set(v8::Local<v8::Value>, v8::Local<v8::Value>)’ is deprecated: Use maybe version [-Wdeprecated-declarations]     results->Set(Nan::New<v8::String>("cts").ToLocalChecked(), Nan::New<v8::Boolean>(data->cts));                                                                                                ^
In file included from /home/iobroker/.cache/node-gyp/12.15.0/include/node/v8-internal.h:14,                 from /home/iobroker/.cache/node-gyp/12.15.0/include/node/v8.h:25,                 from /home/iobroker/.cache/node-gyp/12.15.0/include/node/node.h:63,                 from ../../nan/nan.h:54,                 from ../src/./serialport.h:6,                 from ../src/serialport.cpp:1:/home/iobroker/.cache/node-gyp/12.15.0/include/node/v8.h:3403:22: note: declared here                 bool Set(Local<Value> key, Local<Value> value));                      ^~~/home/iobroker/.cache/node-gyp/12.15.0/include/node/v8config.h:311:3: note: in definition of macro ‘V8_DEPRECATED’   declarator __attribute__((deprecated(message)))   ^~~~~~~~~~
../src/serialport.cpp:330:96: warning: ‘bool v8::Object::Set(v8::Local<v8::Value>, v8::Local<v8::Value>)’ is deprecated: Use maybe version [-Wdeprecated-declarations]     results->Set(Nan::New<v8::String>("dsr").ToLocalChecked(), Nan::New<v8::Boolean>(data->dsr));                                                                                                ^
In file included from /home/iobroker/.cache/node-gyp/12.15.0/include/node/v8-internal.h:14,                 from /home/iobroker/.cache/node-gyp/12.15.0/include/node/v8.h:25,                 from /home/iobroker/.cache/node-gyp/12.15.0/include/node/node.h:63,                 from ../../nan/nan.h:54,                 from ../src/./serialport.h:6,                 from ../src/serialport.cpp:1:/home/iobroker/.cache/node-gyp/12.15.0/include/node/v8.h:3403:22: note: declared here                 bool Set(Local<Value> key, Local<Value> value));                      ^~~/home/iobroker/.cache/node-gyp/12.15.0/include/node/v8config.h:311:3: note: in definition of macro ‘V8_DEPRECATED’   declarator __attribute__((deprecated(message)))   ^~~~~~~~~~
../src/serialport.cpp:331:96: warning: ‘bool v8::Object::Set(v8::Local<v8::Value>, v8::Local<v8::Value>)’ is deprecated: Use maybe version [-Wdeprecated-declarations]     results->Set(Nan::New<v8::String>("dcd").ToLocalChecked(), Nan::New<v8::Boolean>(data->dcd));                                                                                                ^
In file included from /home/iobroker/.cache/node-gyp/12.15.0/include/node/v8-internal.h:14,                 from /home/iobroker/.cache/node-gyp/12.15.0/include/node/v8.h:25,                 from /home/iobroker/.cache/node-gyp/12.15.0/include/node/node.h:63,                 from ../../nan/nan.h:54,                 from ../src/./serialport.h:6,                 from ../src/serialport.cpp:1:/home/iobroker/.cache/node-gyp/12.15.0/include/node/v8.h:3403:22: note: declared here                 bool Set(Local<Value> key, Local<Value> value));                      ^~~/home/iobroker/.cache/node-gyp/12.15.0/include/node/v8config.h:311:3: note: in definition of macro ‘V8_DEPRECATED’   declarator __attribute__((deprecated(message)))   ^~~~~~~~~~
../src/serialport.cpp:336:30: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is deprecated [-Wdeprecated-declarations]   data->callback.Call(2, argv);                              ^In file included from ../src/./serialport.h:6,                 from ../src/serialport.cpp:1:../../nan/nan.h:1740:3: note: declared here   Call(int argc, v8::Local<v8::Value> argv[]) const {   ^~~~
../src/serialport.cpp: In function ‘Nan::NAN_METHOD_RETURN_TYPE GetBaudRate(Nan::NAN_METHOD_ARGS_TYPE)’:../src/serialport.cpp:363:76: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]   uv_queue_work(uv_default_loop(), req, EIO_GetBaudRate, (uv_after_work_cb)EIO_AfterGetBaudRate);                                                                            ^~~~~~~~~~~~~~~~~~~~
../src/serialport.cpp: In function ‘void EIO_AfterGetBaudRate(uv_work_t*)’:../src/serialport.cpp:378:106: warning: ‘bool v8::Object::Set(v8::Local<v8::Value>, v8::Local<v8::Value>)’ is deprecated: Use maybe version [-Wdeprecated-declarations]     results->Set(Nan::New<v8::String>("baudRate").ToLocalChecked(), Nan::New<v8::Integer>(data->baudRate));                                                                                                          ^
In file included from /home/iobroker/.cache/node-gyp/12.15.0/include/node/v8-internal.h:14,                 from /home/iobroker/.cache/node-gyp/12.15.0/include/node/v8.h:25,                 from /home/iobroker/.cache/node-gyp/12.15.0/include/node/node.h:63,                 from ../../nan/nan.h:54,                 from ../src/./serialport.h:6,                 from ../src/serialport.cpp:1:/home/iobroker/.cache/node-gyp/12.15.0/include/node/v8.h:3403:22: note: declared here                 bool Set(Local<Value> key, Local<Value> value));                      ^~~/home/iobroker/.cache/node-gyp/12.15.0/include/node/v8config.h:311:3: note: in definition of macro ‘V8_DEPRECATED’   declarator __attribute__((deprecated(message)))   ^~~~~~~~~~
../src/serialport.cpp:383:30: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is deprecated [-Wdeprecated-declarations]   data->callback.Call(2, argv);                              ^In file included from ../src/./serialport.h:6,                 from ../src/serialport.cpp:1:../../nan/nan.h:1740:3: note: declared here   Call(int argc, v8::Local<v8::Value> argv[]) const {   ^~~~
../src/serialport.cpp: In function ‘Nan::NAN_METHOD_RETURN_TYPE Drain(Nan::NAN_METHOD_ARGS_TYPE)’:../src/serialport.cpp:409:70: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]   uv_queue_work(uv_default_loop(), req, EIO_Drain, (uv_after_work_cb)EIO_AfterDrain);                                                                      ^~~~~~~~~~~~~~
../src/serialport.cpp: In function ‘void EIO_AfterDrain(uv_work_t*)’:../src/serialport.cpp:424:30: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is deprecated [-Wdeprecated-declarations]   data->callback.Call(1, argv);                              ^
In file included from ../src/./serialport.h:6,                 from ../src/serialport.cpp:1:../../nan/nan.h:1740:3: note: declared here   Call(int argc, v8::Local<v8::Value> argv[]) const {   ^~~~
../src/serialport.cpp: At global scope:../src/serialport.cpp:430:28: warning: unnecessary parentheses in declaration of ‘ToParityEnum’ [-Wparentheses] SerialPortParity NAN_INLINE(ToParityEnum(const v8::Local<v8::String>& v8str)) {                            ^
../src/serialport.cpp:449:30: warning: unnecessary parentheses in declaration of ‘ToStopBitEnum’ [-Wparentheses] SerialPortStopBits NAN_INLINE(ToStopBitEnum(double stopBits)) {                              ^
../src/serialport.cpp:460:17: error: variable or field ‘init’ declared void   void init(v8::Handle<v8::Object> target) {                 ^~~~~~
../src/serialport.cpp:460:17: error: ‘Handle’ is not a member of ‘v8’
../src/serialport.cpp:460:34: error: expected primary-expression before ‘>’ token   void init(v8::Handle<v8::Object> target) {                                  ^
../src/serialport.cpp:460:36: error: ‘target’ was not declared in this scope   void init(v8::Handle<v8::Object> target) {                                    ^~~~~~
../src/serialport.cpp:460:36: note: suggested alternative: ‘tzset’   void init(v8::Handle<v8::Object> target) {                                    ^~~~~~                                    tzset
In file included from ../../nan/nan.h:54,                 from ../src/./serialport.h:6,                 from ../src/serialport.cpp:1:../src/serialport.cpp:485:25: error: ‘init’ was not declared in this scope NODE_MODULE(serialport, init);                         ^~~~/home/iobroker/.cache/node-gyp/12.15.0/include/node/node.h:560:36: note: in definition of macro ‘NODE_MODULE_X’       (node::addon_register_func) (regfunc),                          \                                    ^~~~~~~../src/serialport.cpp:485:1: note: in expansion of macro ‘NODE_MODULE’ NODE_MODULE(serialport, init); ^~~~~~~~~~~
../src/serialport.cpp:485:25: note: suggested alternative: ‘int’ NODE_MODULE(serialport, init);                         ^~~~/home/iobroker/.cache/node-gyp/12.15.0/include/node/node.h:560:36: note: in definition of macro ‘NODE_MODULE_X’       (node::addon_register_func) (regfunc),                          \                                    ^~~~~~~../src/serialport.cpp:485:1: note: in expansion of macro ‘NODE_MODULE’ NODE_MODULE(serialport, init); ^~~~~~~~~~~
In file included from /home/iobroker/.cache/node-gyp/12.15.0/include/node/node.h:63,                 from ../../nan/nan.h:54,                 from ../src/./serialport.h:6,                 from ../src/serialport.cpp:1:/home/iobroker/.cache/node-gyp/12.15.0/include/node/v8.h: In instantiation of ‘void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = node::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)]’:/home/iobroker/.cache/node-gyp/12.15.0/include/node/node_object_wrap.h:84:78:   required from here/home/iobroker/.cache/node-gyp/12.15.0/include/node/v8.h:10004:16: warning: cast between incompatible function types from ‘v8::WeakCallbackInfo<node::ObjectWrap>::Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)’} to ‘Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<void>&)’} [-Wcast-function-type]                reinterpret_cast<Callback>(callback), type);                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/iobroker/.cache/node-gyp/12.15.0/include/node/v8.h: In instantiation of ‘void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = Nan::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)]’:../../nan/nan_object_wrap.h:65:61:   required from here/home/iobroker/.cache/node-gyp/12.15.0/include/node/v8.h:10004:16: warning: cast between incompatible function types from ‘v8::WeakCallbackInfo<Nan::ObjectWrap>::Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)’} to ‘Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<void>&)’} [-Wcast-function-type]
make: *** [serialport.target.mk:110: Release/obj.target/serialport/src/serialport.o] Fehler 1
gyp
 ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)gyp ERR! stack     at ChildProcess.emit (events.js:223:5)gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)gyp ERR! System Linux 4.19.97-v7l+gyp
 ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"gyp ERR! cwd /opt/iobroker/node_modules/serialportgyp ERR! node -v v12.15.0gyp ERR! node-gyp -v v5.0.5gyp ERR! not ok 
ERROR: host.raspberrypi Cannot install https://github.com/iobroker-community-adapters/ioBroker.tr-064-community/tarball/b8b8aa25a464f2d81915a1322a3f2739164fcefe: 0
ERROR: process exited with code 25

>
