### ISSUE TITLE
Fehler nach Update auf js-Conrtoller 2.0

### ISSUE THREAD

**Issue by Kampfratte** [soef/ioBroker.tr-064#98]
host.iobroker | 2019-10-18 10:22:54.563 | error | Caught by controller[0]: at process._tickCallback (internal/process/next_tick.js:189:7)
-- | -- | -- | --
host.iobroker | 2019-10-18 10:22:54.563 | error | Caught by controller[0]: at <anonymous>
host.iobroker | 2019-10-18 10:22:54.563 | error | Caught by controller[0]: at promise.then (/opt/iobroker/node_modules/standard-as-callback/built/index.js:19:49)
host.iobroker | 2019-10-18 10:22:54.563 | error | Caught by controller[0]: at tryCatcher (/opt/iobroker/node_modules/standard-as-callback/built/utils.js:11:23)
host.iobroker | 2019-10-18 10:22:54.562 | error | Caught by controller[0]: at client.(anonymous function)._0x161c00 (/opt/iobroker/node_modules/iobroker.objects-redis/index.js:17:70307)
host.iobroker | 2019-10-18 10:22:54.562 | error | Caught by controller[0]: at /opt/iobroker/node_modules/iobroker.tr-064/node_modules/soef/soef.js:609:26
host.iobroker | 2019-10-18 10:22:54.562 | error | Caught by controller[0]: at Devices.setState (/opt/iobroker/node_modules/iobroker.tr-064/node_modules/soef/soef.js:642:36)
host.iobroker | 2019-10-18 10:22:54.561 | error | Caught by controller[0]: TypeError: Cannot read property 'val' of undefined
tr-064.0 | 2019-10-18 10:22:54.538 | info | (12821) Terminated (NO_ERROR): Without reason
tr-064.0 | 2019-10-18 10:22:54.537 | info | (12821) terminating
tr-064.0 | 2019-10-18 10:22:54.532 | error | at process._tickCallback (internal/process/next_tick.js:189:7)
tr-064.0 | 2019-10-18 10:22:54.532 | error | at <anonymous>
tr-064.0 | 2019-10-18 10:22:54.532 | error | at promise.then (/opt/iobroker/node_modules/standard-as-callback/built/index.js:19:49)
tr-064.0 | 2019-10-18 10:22:54.532 | error | at tryCatcher (/opt/iobroker/node_modules/standard-as-callback/built/utils.js:11:23)
tr-064.0 | 2019-10-18 10:22:54.532 | error | at client.(anonymous function)._0x161c00 (/opt/iobroker/node_modules/iobroker.objects-redis/index.js:17:70307)
tr-064.0 | 2019-10-18 10:22:54.532 | error | at /opt/iobroker/node_modules/iobroker.tr-064/node_modules/soef/soef.js:609:26
tr-064.0 | 2019-10-18 10:22:54.532 | error | at Devices.setState (/opt/iobroker/node_modules/iobroker.tr-064/node_modules/soef/soef.js:642:36)
tr-064.0 | 2019-10-18 10:22:54.532 | error | (12821) TypeError: Cannot read property 'val' of undefined
tr-064.0 | 2019-10-18 10:22:54.531 | error | (12821) uncaught exception: Cannot read property 'val' of undefined

**Comment by bergjet** [comment]
Installationsfehler
`$ ./iobroker upgrade tr-064@0.4.18
Update tr-064 from @0.4.18 to @0.4.18
NPM version: 6.11.3
npm install iobroker.tr-064@0.4.18 --loglevel error --production --save --prefix "/opt/iobroker" (System call)
npm
 ERR! code EACCESnpm ERR! syscall accessnpm ERR! path /opt/iobroker/node_modules/iobroker.tr-064/node_modules/array-extnpm ERR! errno -13
npm
 ERR! Error: EACCES: permission denied, access '/opt/iobroker/node_modules/iobroker.tr-064/node_modules/array-ext'npm ERR!  { [Error: EACCES: permission denied, access '/opt/iobroker/node_modules/iobroker.tr-064/node_modules/array-ext']npm ERR!   stack:npm ERR!    'Error: EACCES: permission denied, access \'/opt/iobroker/node_modules/iobroker.tr-064/node_modules/array-ext\'',npm ERR!   errno: -13,npm ERR!   code: 'EACCES',npm ERR!   syscall: 'access',npm
 ERR!   path:npm ERR!    '/opt/iobroker/node_modules/iobroker.tr-064/node_modules/array-ext' }npm ERR! npm ERR! The operation was rejected by your operating system.npm 
ERR! It is likely you do not have the permissions to access this file as the current usernpm ERR! npm ERR! If you believe this might be a permissions issue, please double-check thenpm ERR! permissions of the file and its containing directories, or try runningnpm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:npm ERR!     /home/iobroker/.npm/_logs/2019-10-18T16_19_33_601Z-debug.log
ERROR: host.raspberrypi Cannot install iobroker.tr-064@0.4.18: 243
ERROR: process exited with code 25`

**Comment by axelrathey** [comment]
Läuft hier bei mir mit js-Controller 2.2.7 auch nicht mehr, kann ich also bestätigen

**Comment by Kampfratte** [comment]
@axelrathey ich hab auch den 2.2.7 am laufen und bei mir läuft der Adapter ohne Probleme. Das war ja im Oktober und irgendwie bekam ich ihn wieder zu laufen. Frag mir aber net, was ick da gemacht habe. Seither keine Probleme mehr.

**Comment by axelrathey** [comment]
ich habe jetzt die Version 2.0.3 der community version von tr-064 installiert.
Damit geht es. Ist aber in Handarbeit (installieren aus eigener url und dann beliebig) mit folgender URL
https://github.com/iobroker-community-adapters/ioBroker.tr-064-community
zu installieren. Vorher habe ich die alten Instanzen gelöscht und den alten Adapter deinstalliert
Gruß Axel
